# Generated by Django 5.1.1 on 2024-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_style_product_origin_catcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.FileField(default=1, upload_to='products/images'),
            preserve_default=False,
        ),
    ]
